import { Exercise, ExerciseType } from "@/lib/types";

export const DOMAIN =
  process.env.EXPO_PUBLIC_ENV === "DEVELOPMENT"
    ? process.env.EXPO_PUBLIC_DEV_API_URL
    : process.env.EXPO_PUBLIC_PROD_API_URL;

export const MODELS = {
  gpt: { name: "GPT 4", label: "gpt" },
  gptTurbo: { name: "GPT Turbo", label: "gptTurbo" },
  claude: { name: "Claude", label: "claude" },
  claudeInstant: {
    name: "Claude Instant",
    label: "claudeInstant",
  },
  cohere: { name: "Cohere", label: "cohere" },
  cohereWeb: { name: "Cohere Web", label: "cohereWeb" },
  mistral: { name: "Mistral", label: "mistral" },
  gemini: { name: "Gemini", label: "gemini" },
};

export const CHIP_COLORS = {
  yellow: {
    container: "bg-yellow-50 border-yellow-100 shadow-yellow-100/50",
    text: "rgb(234, 179, 8)",
    bg: "rgb(254, 252, 232)",
    border: "rgb(254, 249, 195)",
    shadow: "rgb(254, 249, 195 / 0.5)",
  },
  orange: {
    text: "rgb(249, 115, 22)",
    bg: "rgb(255, 247, 237)",
    border: "rgb(255, 237, 213)",
    shadow: "rgb(255, 237, 213 / 0.5)",
  },
  blue: {
    container: "border-blue-100 shadow-blue-100/50 text-violet-500",
    text: "rgb(59, 130, 246)",
    bg: "rgb(239, 246, 255)",
    border: "rgb(219, 234, 254)",
    shadow: "rgb(219, 234, 254 / 0.5)",
  },
  teal: {
    container: "bg-teal-50 border-teal-100 shadow-teal-100/50 text-violet-500",
    text: "rgb(20, 184, 166)",
    bg: "rgb(240, 253, 250)",
    border: "rgb(204, 251, 241)",
    shadow: "rgb(204, 251, 241 / 0.5)",
  },
  violet: {
    text: "rgb(139, 92, 246)",
    bg: "rgb(245, 243, 255)",
    border: "rgb(237, 233, 254)",
    shadow: "rgb(237, 233, 254 / 0.5)",
  },
  red: {
    text: "rgb(239, 68, 68)",
    bg: "rgb(254, 242, 242)",
    border: "rgb(254, 226, 226)",
    shadow: "rgb(254, 226, 226 / 0.5)",
  },
  green: {
    container:
      "bg-green-50 shadow-green-100/50 border-green-100 text-green-500",
    text: "rgb(34, 197, 94)",
    bg: "rgb(240, 253, 244)",
    border: "rgb(220, 252, 231)",
    shadow: "rgb(220, 252, 231 / 0.5)",
  },
};

export const EXERCISE_TYPE_MAP: Record<ExerciseType, any> = {
  sets: { icon: "dumbbell", name: "Sets", color: CHIP_COLORS["orange"] },
  interval: {
    icon: "stop-watch",
    name: "Interval",
    color: CHIP_COLORS["blue"],
  },
  duration: { icon: "clock", name: "Duration", color: CHIP_COLORS["green"] },
  misc: { icon: "gift", name: "Misc", color: CHIP_COLORS["yellow"] },
};

export const ACTIVITIES = [
  { name: "Running", type: "cardio" },
  { name: "Walking", type: "cardio" },
  { name: "Jogging", type: "cardio" },
  { name: "Sprinting", type: "cardio" },
  { name: "Cycling (Outdoor)", type: "cardio" },
  { name: "Stationary Biking", type: "cardio" },
  { name: "Elliptical Training", type: "cardio" },
  { name: "Treadmill Running", type: "cardio" },
  { name: "Treadmill Walking", type: "cardio" },
  { name: "Stair Climbing", type: "cardio" },
  { name: "Hiking", type: "cardio" },
  { name: "Rowing (Outdoor)", type: "cardio" },
  { name: "Rowing Machine", type: "cardio" },
  { name: "Swimming", type: "cardio" },
  { name: "Jumping Rope", type: "cardio" },
  { name: "Dance Aerobics", type: "cardio" },
  { name: "High-Intensity Interval Training (HIIT)", type: "cardio" },
  { name: "Kickboxing", type: "cardio" },
  { name: "Zumba", type: "cardio" },
  { name: "Aerobic Dance", type: "cardio" },
  { name: "Bodyweight Exercises", type: "strength" },
  { name: "Weightlifting", type: "strength" },
  { name: "Powerlifting", type: "strength" },
  { name: "Olympic Lifting", type: "strength" },
  { name: "Kettlebell Training", type: "strength" },
  { name: "Dumbbell Workouts", type: "strength" },
  { name: "Barbell Workouts", type: "strength" },
  { name: "Resistance Band Training", type: "strength" },
  { name: "TRX Suspension Training", type: "strength" },
  { name: "Functional Training", type: "strength" },
  { name: "Yoga", type: "flexibility" },
  { name: "Pilates", type: "flexibility" },
  { name: "Stretching", type: "flexibility" },
  { name: "Tai Chi", type: "flexibility" },
  { name: "Barre Workouts", type: "flexibility" },
  { name: "Basketball", type: "sports" },
  { name: "Soccer", type: "sports" },
  { name: "Tennis", type: "sports" },
  { name: "Badminton", type: "sports" },
  { name: "Volleyball", type: "sports" },
  { name: "Rugby", type: "sports" },
  { name: "Cricket", type: "sports" },
  { name: "Baseball", type: "sports" },
  { name: "Softball", type: "sports" },
  { name: "American Football", type: "sports" },
  { name: "Table Tennis", type: "sports" },
  { name: "Squash", type: "sports" },
  { name: "Racquetball", type: "sports" },
  { name: "Golf", type: "sports" },
  { name: "Ultimate Frisbee", type: "sports" },
  { name: "Handball", type: "sports" },
  { name: "Surfing", type: "water sports" },
  { name: "Paddleboarding", type: "water sports" },
  { name: "Kayaking", type: "water sports" },
  { name: "Canoeing", type: "water sports" },
  { name: "Water Polo", type: "water sports" },
  { name: "Scuba Diving", type: "water sports" },
  { name: "Snorkeling", type: "water sports" },
  { name: "Sailing", type: "water sports" },
  { name: "Windsurfing", type: "water sports" },
  { name: "Skiing (Alpine)", type: "winter sports" },
  { name: "Cross-Country Skiing", type: "winter sports" },
  { name: "Snowboarding", type: "winter sports" },
  { name: "Ice Skating", type: "winter sports" },
  { name: "Figure Skating", type: "winter sports" },
  { name: "Curling", type: "winter sports" },
  { name: "Snowshoeing", type: "winter sports" },
  { name: "Karate", type: "martial arts" },
  { name: "Judo", type: "martial arts" },
  { name: "Taekwondo", type: "martial arts" },
  { name: "Kung Fu", type: "martial arts" },
  { name: "Brazilian Jiu-Jitsu", type: "martial arts" },
  { name: "Wrestling", type: "martial arts" },
  { name: "Boxing", type: "martial arts" },
  { name: "Muay Thai", type: "martial arts" },
  { name: "Mixed Martial Arts (MMA)", type: "martial arts" },
  { name: "Spin Class", type: "group fitness" },
  { name: "Boot Camp", type: "group fitness" },
  { name: "Circuit Training", type: "group fitness" },
  { name: "BodyPump", type: "group fitness" },
  { name: "Step Aerobics", type: "group fitness" },
  { name: "Aqua Aerobics", type: "group fitness" },
  { name: "CrossFit", type: "group fitness" },
  { name: "Meditation", type: "mind-body" },
  { name: "Breathwork", type: "mind-body" },
  { name: "Qigong", type: "mind-body" },
  { name: "Rock Climbing", type: "outdoor" },
  { name: "Bouldering", type: "outdoor" },
  { name: "Mountain Biking", type: "outdoor" },
  { name: "Trail Running", type: "outdoor" },
  { name: "Orienteering", type: "outdoor" },
  { name: "Geocaching", type: "outdoor" },
  { name: "Horseback Riding", type: "outdoor" },
  { name: "Prenatal Fitness", type: "special populations" },
  { name: "Postnatal Fitness", type: "special populations" },
  { name: "Senior Fitness", type: "special populations" },
  { name: "Adaptive Fitness (for disabilities)", type: "special populations" },
  { name: "Functional Movement Training", type: "hybrid and miscellaneous" },
  { name: "Parkour", type: "hybrid and miscellaneous" },
  { name: "Animal Flow", type: "hybrid and miscellaneous" },
  { name: "Obstacle Course Training", type: "hybrid and miscellaneous" },
  { name: "TRX Yoga", type: "hybrid and miscellaneous" },
  { name: "Pilates Reformer", type: "hybrid and miscellaneous" },
  { name: "Aqua Zumba", type: "hybrid and miscellaneous" },
  { name: "Hot Yoga", type: "hybrid and miscellaneous" },
  { name: "Chair Yoga", type: "hybrid and miscellaneous" },
  { name: "Silent Disco Workouts", type: "hybrid and miscellaneous" },
  { name: "Virtual Reality Workouts", type: "hybrid and miscellaneous" },
  { name: "Home Cardio", type: "home workouts" },
  { name: "Home Strength Training", type: "home workouts" },
  { name: "Home Yoga", type: "home workouts" },
  { name: "Home Pilates", type: "home workouts" },
  { name: "Home HIIT", type: "home workouts" },
  { name: "Home Dance Workouts", type: "home workouts" },
];
