export const ACTIVITIES = [
  { name: "Running", type: "cardio" },
  { name: "Walking", type: "cardio" },
  { name: "Jogging", type: "cardio" },
  { name: "Sprinting", type: "cardio" },
  { name: "Cycling (Outdoor)", type: "cardio" },
  { name: "Stationary Biking", type: "cardio" },
  { name: "Elliptical Training", type: "cardio" },
  { name: "Treadmill Running", type: "cardio" },
  { name: "Treadmill Walking", type: "cardio" },
  { name: "Stair Climbing", type: "cardio" },
  { name: "Hiking", type: "cardio" },
  { name: "Rowing (Outdoor)", type: "cardio" },
  { name: "Rowing Machine", type: "cardio" },
  { name: "Swimming", type: "cardio" },
  { name: "Jumping Rope", type: "cardio" },
  { name: "Dance Aerobics", type: "cardio" },
  { name: "High-Intensity Interval Training (HIIT)", type: "cardio" },
  { name: "Kickboxing", type: "cardio" },
  { name: "Zumba", type: "cardio" },
  { name: "Aerobic Dance", type: "cardio" },
  { name: "Bodyweight Exercises", type: "strength" },
  { name: "Weightlifting", type: "strength" },
  { name: "Powerlifting", type: "strength" },
  { name: "Olympic Lifting", type: "strength" },
  { name: "Kettlebell Training", type: "strength" },
  { name: "Dumbbell Workouts", type: "strength" },
  { name: "Barbell Workouts", type: "strength" },
  { name: "Resistance Band Training", type: "strength" },
  { name: "TRX Suspension Training", type: "strength" },
  { name: "Functional Training", type: "strength" },
  { name: "Yoga", type: "flexibility" },
  { name: "Pilates", type: "flexibility" },
  { name: "Stretching", type: "flexibility" },
  { name: "Tai Chi", type: "flexibility" },
  { name: "Barre Workouts", type: "flexibility" },
  { name: "Basketball", type: "sports" },
  { name: "Soccer", type: "sports" },
  { name: "Tennis", type: "sports" },
  { name: "Badminton", type: "sports" },
  { name: "Volleyball", type: "sports" },
  { name: "Rugby", type: "sports" },
  { name: "Cricket", type: "sports" },
  { name: "Baseball", type: "sports" },
  { name: "Softball", type: "sports" },
  { name: "American Football", type: "sports" },
  { name: "Table Tennis", type: "sports" },
  { name: "Squash", type: "sports" },
  { name: "Racquetball", type: "sports" },
  { name: "Golf", type: "sports" },
  { name: "Ultimate Frisbee", type: "sports" },
  { name: "Handball", type: "sports" },
  { name: "Surfing", type: "water sports" },
  { name: "Paddleboarding", type: "water sports" },
  { name: "Kayaking", type: "water sports" },
  { name: "Canoeing", type: "water sports" },
  { name: "Water Polo", type: "water sports" },
  { name: "Scuba Diving", type: "water sports" },
  { name: "Snorkeling", type: "water sports" },
  { name: "Sailing", type: "water sports" },
  { name: "Windsurfing", type: "water sports" },
  { name: "Skiing (Alpine)", type: "winter sports" },
  { name: "Cross-Country Skiing", type: "winter sports" },
  { name: "Snowboarding", type: "winter sports" },
  { name: "Ice Skating", type: "winter sports" },
  { name: "Figure Skating", type: "winter sports" },
  { name: "Curling", type: "winter sports" },
  { name: "Snowshoeing", type: "winter sports" },
  { name: "Karate", type: "martial arts" },
  { name: "Judo", type: "martial arts" },
  { name: "Taekwondo", type: "martial arts" },
  { name: "Kung Fu", type: "martial arts" },
  { name: "Brazilian Jiu-Jitsu", type: "martial arts" },
  { name: "Wrestling", type: "martial arts" },
  { name: "Boxing", type: "martial arts" },
  { name: "Muay Thai", type: "martial arts" },
  { name: "Mixed Martial Arts (MMA)", type: "martial arts" },
  { name: "Spin Class", type: "group fitness" },
  { name: "Boot Camp", type: "group fitness" },
  { name: "Circuit Training", type: "group fitness" },
  { name: "BodyPump", type: "group fitness" },
  { name: "Step Aerobics", type: "group fitness" },
  { name: "Aqua Aerobics", type: "group fitness" },
  { name: "CrossFit", type: "group fitness" },
  { name: "Meditation", type: "mind-body" },
  { name: "Breathwork", type: "mind-body" },
  { name: "Qigong", type: "mind-body" },
  { name: "Rock Climbing", type: "outdoor" },
  { name: "Bouldering", type: "outdoor" },
  { name: "Mountain Biking", type: "outdoor" },
  { name: "Trail Running", type: "outdoor" },
  { name: "Orienteering", type: "outdoor" },
  { name: "Geocaching", type: "outdoor" },
  { name: "Horseback Riding", type: "outdoor" },
  { name: "Prenatal Fitness", type: "special populations" },
  { name: "Postnatal Fitness", type: "special populations" },
  { name: "Senior Fitness", type: "special populations" },
  { name: "Adaptive Fitness (for disabilities)", type: "special populations" },
  { name: "Functional Movement Training", type: "hybrid and miscellaneous" },
  { name: "Parkour", type: "hybrid and miscellaneous" },
  { name: "Animal Flow", type: "hybrid and miscellaneous" },
  { name: "Obstacle Course Training", type: "hybrid and miscellaneous" },
  { name: "TRX Yoga", type: "hybrid and miscellaneous" },
  { name: "Pilates Reformer", type: "hybrid and miscellaneous" },
  { name: "Aqua Zumba", type: "hybrid and miscellaneous" },
  { name: "Hot Yoga", type: "hybrid and miscellaneous" },
  { name: "Chair Yoga", type: "hybrid and miscellaneous" },
  { name: "Silent Disco Workouts", type: "hybrid and miscellaneous" },
  { name: "Virtual Reality Workouts", type: "hybrid and miscellaneous" },
  { name: "Home Cardio", type: "home workouts" },
  { name: "Home Strength Training", type: "home workouts" },
  { name: "Home Yoga", type: "home workouts" },
  { name: "Home Pilates", type: "home workouts" },
  { name: "Home HIIT", type: "home workouts" },
  { name: "Home Dance Workouts", type: "home workouts" },
];
